### ISSUE TITLE
Couldn't recognize cards with card number length other than 16

### ISSUE THREAD

**Issue by intrueder** [pochtalyon33/KottansTasks#1]
According to wiki page https://en.wikipedia.org/wiki/Bank_card_number, for example, American Express cards have 15 digit number, VISA and Maestro have variable number length. All such numbers should be supported

**Comment by m-ant** [comment]
Length problem fixed.
Credit number is valid if length equal 12..19.
Modified functions `GetCreditCardVendor`, added check the length of credit number for vendors. 
Example: If entered credit number has INN like Visa's INN, but length entered card number is't equal length Visa credit numbres, input will be incorrect and user will write credit number again.

**Comment by m-ant** [comment]
I found one more problem. It fixed too.
Added checking the possible to generate next credit number.
Last commit - https://github.com/pochtalyon33/KottansTasks/commit/2122c13618cd95c9001321762e5ae58954482f0f
