### ISSUE TITLE
Invalid numbers are recognized

### ISSUE THREAD

**Issue by intrueder** [pochtalyon33/KottansTasks#2]
Pass `"50000000000006114"` to `GetCreditCardVendor` method
Expected result: "Unknown" (because number is invalid)
Actual result: "Maestro"

**Comment by m-ant** [comment]
It's hard to understand  commit on screenshot for me.
Application should work more then one iteration for comfortable testing?
![screenshot from 2016-05-09 18 38 29](https://cloud.githubusercontent.com/assets/18424965/15118539/4372e0ce-1615-11e6-97c2-c9475d15d571.png)
If I'm right, check second branch https://github.com/pochtalyon33/KottansTasks/tree/endless_menu_loop  and if I'm mistake, explain a bit about this problem, please.

**Comment by intrueder** [comment]
Code comment was not related to this issue. When I see `while`, I expect a loop :) but in current version there is no code that changes `menu` variable. And yes, it is for more comfortable testing only. Code in another brunch looks better, thanks!
